import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { NextUIProvider } from '@nextui-org/react';
import "./globals.css";

//import CartProvider from "@/store/CartProvider";
import { CartProvider } from "@/store/CartProvider";
import { Toaster, ToastIcon } from "react-hot-toast";
import { SessionProvider } from "next-auth/react"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className="bg-gradient-to-r from-indigo-40 via-purple-40 to-pink-40">
      
      <CartProvider>
     
      <NextUIProvider>
        
        {children}
        <Toaster position="top-right" />
        </NextUIProvider> 

       </CartProvider>
      
        </body>
    </html>
  );
}
